apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testgo1
  janus-idp.io/tekton: testgo1
  backstage.io/kubernetes-id: testgo1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testgo1
resources:
- deployment.yaml
- route.yaml
- service.yaml
